#!/bin/bash

# This script takes the folder names (SAMPLES in this case) and attach to the files generated by SMETANA

# Changing the "Internal Field Separator"
OLDIFS="$IFS"
IFS=$'\n'

# List the directories into a txt file
ls -d */ | sed 's#/##' > folders.txt


for i in $(cat folders.txt)
    do
        SAMPLE=$(echo $i)
        #echo $SAMPLE
        GLOBAL=$(echo "${SAMPLE}_global.tsv")
        DETAILED=$(echo "${SAMPLE}_detailed.tsv")
        
        cp $SAMPLE/_global.tsv $GLOBAL
        cp $SAMPLE/_detailed.tsv $DETAILED
    done

IFS="$OLDIFS"
